name: Deploy Website

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -input=false

      - name: Terraform Apply (no infra, just pass vars)
        working-directory: ./terraform
        env:
          TF_VAR_bucket_name: ${{ secrets.BUCKET_NAME }}
          TF_VAR_react_app_test_environment: ${{ secrets.REACT_APP_TEST_ENVIRONMENT }}
        run: terraform apply -input=false -auto-approve

      - name: Export Terraform outputs to GITHUB_ENV
        id: tf-out
        working-directory: ./terraform
        run: |
          echo "BUCKET_NAME=$(terraform output -raw bucket_name)" >> $GITHUB_ENV
          echo "REACT_APP_TEST_ENVIRONMENT=$(terraform output -raw react_app_test_environment)" >> $GITHUB_ENV

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Modules
        run: npm ci

      - name: Build Application
        env:
          REACT_APP_TEST_ENVIRONMENT: ${{ env.REACT_APP_TEST_ENVIRONMENT }}
        run: npm run build

      - name: Deploy to S3
        run: aws s3 sync ./build s3://$BUCKET_NAME

      # - name: Create Cloudfront Invalidation
      #   run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
